name = "diet"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

# Database: created once with `wrangler d1 create diet`, then paste the id below.
[[d1_databases]]
binding = "DB"
database_name = "diet"
database_id = "e9fbf1d3-5a6c-4b25-a6f0-f7be8e90a278"
migrations_dir = "migrations"
